### ISSUE TITLE
Box shadow is too dense

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/flipkart-html-css#3]
Expected
![image](https://user-images.githubusercontent.com/75989919/212819662-f6e46f47-8980-44fb-91bd-b4374d1b0ea7.png)

Actual
![image](https://user-images.githubusercontent.com/75989919/212819609-b316457c-f9ab-4b9a-acb4-85ea3be6eccc.png)

**Comment by ashishkk22** [comment]
--> Changed as per the expected shadow.
![image](https://user-images.githubusercontent.com/83124264/212975719-dc39cd74-df05-4b82-a1dc-bfc9d2d59cdf.png)
