### ISSUE TITLE
Extra margin is present before input placeholder

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/flipkart-html-css#4]
![image](https://user-images.githubusercontent.com/75989919/212819992-611a70be-62ac-4079-b924-eb7b4c453d1e.png)

**Comment by ashishkk22** [comment]
removed the extra margin in the input field
![image](https://user-images.githubusercontent.com/83124264/212976500-01d34d54-1dea-42cd-a9e5-ba34a0cf923f.png)
