### ISSUE TITLE
Missing italic styles in logo

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/flipkart-html-css#6]
![image](https://user-images.githubusercontent.com/75989919/212820959-b07770e3-9dc6-474f-89c7-279ba64cff21.png)

Explore plus text should be italic as per design

**Comment by ashishkk22** [comment]
added font style as italic in logo section.
![image](https://user-images.githubusercontent.com/83124264/212980747-ceb88307-0843-4214-a867-0d4c08d3887d.png)
