### ISSUE TITLE
Sub title is missing in Winter Essentials section

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/flipkart-html-css#7]
Expected
![image](https://user-images.githubusercontent.com/75989919/212821312-e50af8c5-53da-46d9-bbc6-2c2e42ce0c7e.png)

Actual
![image](https://user-images.githubusercontent.com/75989919/212821388-1fbe397e-4d58-4e76-9dcd-9c55661c9452.png)

**Comment by ashishkk22** [comment]
Added the subtitle in the Winter Essentials section.
