### ISSUE TITLE
Line height issue

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/flipkart-html-css#8]
Expected
![image](https://user-images.githubusercontent.com/75989919/212821726-5869d50c-9406-4987-81f9-58d33e1e6fee.png)

Actual
![image](https://user-images.githubusercontent.com/75989919/212821641-2c588894-2295-40b9-b405-826d10705951.png)

**Comment by ashishkk22** [comment]
Added the line height in the deals of the day's card.
